# Generated by Django 5.1.7 on 2025-05-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
    ]
