# Generated by Django 5.1.7 on 2025-04-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_image_product_image_local_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_local',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
