# Generated by Django 5.1.7 on 2025-04-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_userprofile_avatar_alter_userprofile_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='group',
            new_name='about',
        ),
    ]
