# Generated by Django 5.1.7 on 2025-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_broadcastmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastmessage',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'Реклама'},
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='broadcasts/'),
        ),
    ]
